#!/bin/bash
#Salve esse arquivo como geradorovpn.sh e execute o comando "chmod +x geradorovpn.sh"
#Modo de execução: ./geradorovpn.sh <nome-do-certificado>
touch $1.ovpn
printf '%sclient
remote <servidor remoto> <porta>
dev tun
proto <protocolo>
comp-lzo yes
persist-tun
persist-key\n' >> $1.ovpn

echo "<ca>" >> $1.ovpn
cat ca.crt >> $1.ovpn
echo "</ca>" >> $1.ovpn

echo "<cert>" >> $1.ovpn
cat $1.crt >> $1.ovpn
echo "</cert>" >> $1.ovpn

echo "<key>" >> $1.ovpn
cat $1.key >> $1.ovpn
echo "</key>" >> $1.ovpn
